# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f26f8eac3ffb10cb3b56d5c8d61022663f4ea12e2166f04cde6cc66b6b8a55588a4c3fca708de025780e8b1137f77a899f885f091a66c7eac8e1c59c966cb7c9

test:
  secret_key_base: 77281a26725ff5a1a0a4fcf9e627b5f8689ef8f278e89fe937d43fd3c28474076acfd894aaea11d224d0c4f593af4983083eb405804123fb18beef1808dc0c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
